baseURL: https://kendrickherz.github.io
languageCode: en-us
title: "Kendrick's page"
theme: "toha (slightly modified version by Kendrick Herzberg)"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
DefaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
  fr:
    languageName: French
    weight: 2

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  goldmark:
    renderer:
      unsafe: true
  blackfriday:
    plainIDAnchors: true
    hrefTargetBlank: true


# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # background
  Background: images/wall-toulouse.jpg
  # GitHub repo URL of your site
  gitRepo: https://github.com/kendrickherz/portfolio.git

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: False